server:
  port: 9999

spring:
  application:
    name: zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
zuul:
  routes:
    log:
      path: /api/log/**
      serviceId: log
    ht:
      path: /ht/**
      serviceId: ht
  strip-prefix: true
  sensitive-headers:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
rest:
  api:
    names: ht,log
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 240000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
